@startuml
!theme plain
top to bottom direction
skinparam linetype ortho

class alembic_version {
   version_num: varchar(32)
}
class categories {
   name: varchar(100)
   description: varchar(255)
   created_at: datetime
   updated_at: datetime
   id: integer
}
class game_categories {
   game_id: integer
   category_id: integer
   created_at: datetime
   updated_at: datetime
   id: integer
}
class game_genres {
   game_id: integer
   genre_id: integer
   created_at: datetime
   updated_at: datetime
   id: integer
}
class game_metrics {
   game_id: integer
   recommendations_count: integer
   metacritic_score: integer
   review_score: float
   review_count: integer
   peak_players_all_time: integer
   last_updated: datetime
   created_at: datetime
   updated_at: datetime
   id: integer
}
class game_platforms {
   game_id: integer
   platform_id: integer
   supported: boolean
   created_at: datetime
   updated_at: datetime
   id: integer
}
class game_types {
   name: varchar(100)
   description: varchar(255)
   created_at: datetime
   updated_at: datetime
   id: integer
}
class games {
   app_id: integer
   name: varchar(255)
   type_id: integer
   is_free: boolean
   release_date: datetime
   coming_soon: boolean
   controller_support: varchar(50)
   created_at: datetime
   updated_at: datetime
   id: integer
}
class genres {
   name: varchar(100)
   description: varchar(255)
   created_at: datetime
   updated_at: datetime
   id: integer
}
class platforms {
   name: varchar(100)
   description: varchar(255)
   created_at: datetime
   updated_at: datetime
   id: integer
}
class player_count_history {
   game_id: integer
   player_count: integer
   recorded_at: datetime
   created_at: datetime
   updated_at: datetime
   id: integer
}
class price_history {
   game_id: integer
   currency: varchar(3)
   price_final: integer
   discount_percent: integer
   recorded_at: datetime
   created_at: datetime
   updated_at: datetime
   id: integer
}
class sqlite_master {
   type: text
   name: text
   tbl_name: text
   rootpage: int
   sql: text
}

game_categories       -[#595959,plain]-^  categories           : "category_id:id"
game_categories       -[#595959,plain]-^  games                : "game_id:id"
game_genres           -[#595959,plain]-^  games                : "game_id:id"
game_genres           -[#595959,plain]-^  genres               : "genre_id:id"
game_metrics          -[#595959,plain]-^  games                : "game_id:id"
game_platforms        -[#595959,plain]-^  games                : "game_id:id"
game_platforms        -[#595959,plain]-^  platforms            : "platform_id:id"
games                 -[#595959,plain]-^  game_types           : "type_id:id"
player_count_history  -[#595959,plain]-^  games                : "game_id:id"
price_history         -[#595959,plain]-^  games                : "game_id:id"
@enduml