"""update db analysis models

Revision ID: 242acb88d9c2
Revises: d9f2fd2200d9
Create Date: 2025-10-22 22:48:58.080426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '242acb88d9c2'
down_revision: Union[str, Sequence[str], None] = 'd9f2fd2200d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_chunks', 'last_processed_app_id')
    op.drop_column('game_data_analysis', 'platforms')
    op.drop_column('game_data_analysis', 'categories')
    op.drop_column('game_data_analysis', 'version')
    op.drop_column('game_data_analysis', 'genres')
    op.drop_column('game_data_analysis', 'achievements')
    op.drop_column('game_data_analysis', 'stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_data_analysis', sa.Column('stats', sqlite.JSON(), nullable=True))
    op.add_column('game_data_analysis', sa.Column('achievements', sqlite.JSON(), nullable=True))
    op.add_column('game_data_analysis', sa.Column('genres', sqlite.JSON(), nullable=True))
    op.add_column('game_data_analysis', sa.Column('version', sa.INTEGER(), nullable=True))
    op.add_column('game_data_analysis', sa.Column('categories', sqlite.JSON(), nullable=True))
    op.add_column('game_data_analysis', sa.Column('platforms', sqlite.JSON(), nullable=True))
    op.add_column('analysis_chunks', sa.Column('last_processed_app_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
