"""Fix game add name into analysis model

Revision ID: 29142a773d9f
Revises: 0c4571384db5
Create Date: 2025-10-26 23:47:21.106033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29142a773d9f'
down_revision: Union[str, Sequence[str], None] = '0c4571384db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_data_analysis', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_data_analysis', 'name')
    # ### end Alembic commands ###
