"""init db analysis models

Revision ID: 2a721798abf9
Revises: 
Create Date: 2025-10-20 00:19:16.130675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a721798abf9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_chunks',
    sa.Column('app_ids', sa.JSON(), nullable=False),
    sa.Column('start_app_id', sa.Integer(), nullable=True),
    sa.Column('end_app_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('null_count', sa.Integer(), nullable=True),
    sa.Column('not_null_count', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_chunk_end', 'analysis_chunks', ['end_app_id'], unique=False)
    op.create_index('idx_analysis_chunk_start', 'analysis_chunks', ['start_app_id'], unique=False)
    op.create_index('idx_analysis_chunk_status', 'analysis_chunks', ['status'], unique=False)
    op.create_table('game_data_analysis',
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['analysis_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_data_app', 'game_data_analysis', ['app_id'], unique=False)
    op.create_index('idx_game_data_chunk', 'game_data_analysis', ['chunk_id'], unique=False)
    op.create_index('idx_game_data_status', 'game_data_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_game_data_analysis_app_id'), 'game_data_analysis', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_data_analysis_app_id'), table_name='game_data_analysis')
    op.drop_index('idx_game_data_status', table_name='game_data_analysis')
    op.drop_index('idx_game_data_chunk', table_name='game_data_analysis')
    op.drop_index('idx_game_data_app', table_name='game_data_analysis')
    op.drop_table('game_data_analysis')
    op.drop_index('idx_analysis_chunk_status', table_name='analysis_chunks')
    op.drop_index('idx_analysis_chunk_start', table_name='analysis_chunks')
    op.drop_index('idx_analysis_chunk_end', table_name='analysis_chunks')
    op.drop_table('analysis_chunks')
    # ### end Alembic commands ###
