"""Update logic for models

Revision ID: 4da6ea73c6ed
Revises: 
Create Date: 2025-10-26 22:52:28.006159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da6ea73c6ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_chunks',
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('started_at IS NULL OR finished_at IS NULL OR started_at <= finished_at', name='check_timeline_order'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_chunk_processed_by', 'analysis_chunks', ['processed_by'], unique=False)
    op.create_index('idx_analysis_chunk_status', 'analysis_chunks', ['status'], unique=False)
    op.create_table('game_data_analysis',
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['analysis_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_game_data_app', 'game_data_analysis', ['app_id'], unique=False)
    op.create_index('idx_game_data_chunk', 'game_data_analysis', ['chunk_id'], unique=False)
    op.create_index('idx_game_data_status', 'game_data_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_game_data_analysis_app_id'), 'game_data_analysis', ['app_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_data_analysis_app_id'), table_name='game_data_analysis')
    op.drop_index('idx_game_data_status', table_name='game_data_analysis')
    op.drop_index('idx_game_data_chunk', table_name='game_data_analysis')
    op.drop_index('idx_game_data_app', table_name='game_data_analysis')
    op.drop_table('game_data_analysis')
    op.drop_index('idx_analysis_chunk_status', table_name='analysis_chunks')
    op.drop_index('idx_analysis_chunk_processed_by', table_name='analysis_chunks')
    op.drop_table('analysis_chunks')
    # ### end Alembic commands ###
