"""Add unique constraint for steam ids

Revision ID: d6c6b0495720
Revises: bfcc842bb084
Create Date: 2025-11-12 21:01:44.165670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c6b0495720'
down_revision: Union[str, Sequence[str], None] = 'bfcc842bb084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_data_analysis_app_id'), table_name='game_data_analysis')
    op.create_index(op.f('ix_game_data_analysis_app_id'), 'game_data_analysis', ['app_id'], unique=True)
    op.drop_index(op.f('ix_user_data_analysis_steam_id'), table_name='user_data_analysis')
    op.create_index(op.f('ix_user_data_analysis_steam_id'), 'user_data_analysis', ['steam_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_analysis_steam_id'), table_name='user_data_analysis')
    op.create_index(op.f('ix_user_data_analysis_steam_id'), 'user_data_analysis', ['steam_id'], unique=False)
    op.drop_index(op.f('ix_game_data_analysis_app_id'), table_name='game_data_analysis')
    op.create_index(op.f('ix_game_data_analysis_app_id'), 'game_data_analysis', ['app_id'], unique=False)
    # ### end Alembic commands ###
