"""update db analysis models

Revision ID: d9f2fd2200d9
Revises: 2a721798abf9
Create Date: 2025-10-22 00:42:41.079653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9f2fd2200d9'
down_revision: Union[str, Sequence[str], None] = '2a721798abf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_chunks', sa.Column('last_processed_app_id', sa.Integer(), nullable=True))
    op.add_column('game_data_analysis', sa.Column('processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_data_analysis', 'processed')
    op.drop_column('analysis_chunks', 'last_processed_app_id')
    # ### end Alembic commands ###
