"""add user-analysis models

Revision ID: fdefe9555ce4
Revises: 29142a773d9f
Create Date: 2025-11-04 00:26:32.384081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdefe9555ce4'
down_revision: Union[str, Sequence[str], None] = '29142a773d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data_analysis',
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['analysis_user_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_data_app', 'user_data_analysis', ['steam_id'], unique=False)
    op.create_index('idx_user_data_chunk', 'user_data_analysis', ['chunk_id'], unique=False)
    op.create_index('idx_user_data_status', 'user_data_analysis', ['status'], unique=False)
    op.create_index(op.f('ix_user_data_analysis_steam_id'), 'user_data_analysis', ['steam_id'], unique=False)
    op.create_index('idx_analysis_user_chunk_processed_by', 'analysis_user_chunks', ['processed_by'], unique=False)
    op.create_index('idx_analysis_user_chunk_status', 'analysis_user_chunks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_user_chunk_status', table_name='analysis_user_chunks')
    op.drop_index('idx_analysis_user_chunk_processed_by', table_name='analysis_user_chunks')
    op.drop_index(op.f('ix_user_data_analysis_steam_id'), table_name='user_data_analysis')
    op.drop_index('idx_user_data_status', table_name='user_data_analysis')
    op.drop_index('idx_user_data_chunk', table_name='user_data_analysis')
    op.drop_index('idx_user_data_app', table_name='user_data_analysis')
    op.drop_table('user_data_analysis')
    # ### end Alembic commands ###
