"""Delete at_created fields

Revision ID: 23d854543c7d
Revises: 458183a71964
Create Date: 2025-10-04 23:45:01.231970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d854543c7d'
down_revision: Union[str, Sequence[str], None] = '458183a71964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_player_history_date'), table_name='player_count_history')
    op.create_index('idx_player_history_date', 'player_count_history', ['created_at'], unique=False)
    op.drop_column('player_count_history', 'recorded_at')
    op.add_column('price_history', sa.Column('initial', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_price_history_date'), table_name='price_history')
    op.create_index('idx_price_history_date', 'price_history', ['created_at'], unique=False)
    op.drop_column('price_history', 'recorded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('recorded_at', sa.DATETIME(), nullable=False))
    op.drop_index('idx_price_history_date', table_name='price_history')
    op.create_index(op.f('idx_price_history_date'), 'price_history', ['recorded_at'], unique=False)
    op.drop_column('price_history', 'initial')
    op.add_column('player_count_history', sa.Column('recorded_at', sa.DATETIME(), nullable=False))
    op.drop_index('idx_player_history_date', table_name='player_count_history')
    op.create_index(op.f('idx_player_history_date'), 'player_count_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###
