"""Delete name from dict models fields

Revision ID: 2f93b3291309
Revises: 23d854543c7d
Create Date: 2025-10-06 19:28:50.698206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f93b3291309'
down_revision: Union[str, Sequence[str], None] = '23d854543c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_description'), 'categories', ['description'], unique=True)
    op.drop_column('categories', 'name')
    op.drop_column('game_metrics', 'last_updated')
    op.drop_index(op.f('ix_game_types_name'), table_name='game_types')
    op.create_index(op.f('ix_game_types_description'), 'game_types', ['description'], unique=True)
    op.drop_column('game_types', 'name')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.create_index(op.f('ix_genres_description'), 'genres', ['description'], unique=True)
    op.drop_column('genres', 'name')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.create_index(op.f('ix_platforms_description'), 'platforms', ['description'], unique=True)
    op.drop_column('platforms', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_platforms_description'), table_name='platforms')
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=1)
    op.add_column('genres', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_genres_description'), table_name='genres')
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=1)
    op.add_column('game_types', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_game_types_description'), table_name='game_types')
    op.create_index(op.f('ix_game_types_name'), 'game_types', ['name'], unique=1)
    op.add_column('game_metrics', sa.Column('last_updated', sa.DATETIME(), nullable=False))
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_index(op.f('ix_categories_description'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=1)
    # ### end Alembic commands ###
