"""add ratings

Revision ID: 652083587cb1
Revises: a0103b552f6e
Create Date: 2025-12-08 00:05:11.714018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652083587cb1'
down_revision: Union[str, Sequence[str], None] = 'a0103b552f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.create_table('rating_names',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )

    op.create_table('ratings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('rating_name_id', sa.Integer(), nullable=False),
                    sa.Column('rating', sa.String(length=50), nullable=True),
                    sa.Column('req_age', sa.Integer(), nullable=True),
                    sa.Column('banned', sa.Boolean(), nullable=True),
                    sa.Column('rating_generated', sa.Boolean(), nullable=True),
                    sa.Column('use_age_gate', sa.Boolean(), nullable=True),
                    sa.Column('descriptors', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['rating_name_id'], ['rating_names.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('game_id', 'rating_name_id', name='uq_game_rating_org')
                    )

    op.create_index('idx_ratings_game', 'ratings', ['game_id'])
    op.create_index('idx_ratings_name', 'ratings', ['rating_name_id'])
    op.create_index('idx_ratings_rating', 'ratings', ['rating'])
    op.create_index('idx_ratings_banned', 'ratings', ['banned'])



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    if bind.engine.name == 'sqlite':
        with op.batch_alter_table('friends') as batch_op:
            batch_op.drop_constraint('uq_friends_pair', type_='unique')
    else:
        op.drop_constraint('uq_friends_pair', 'friends', type_='unique')
    # ### end Alembic commands ###
