"""add ratings

Revision ID: 9b18da156691
Revises: a0103b552f6e
Create Date: 2025-12-08 21:49:21.438747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b18da156691'
down_revision: Union[str, Sequence[str], None] = 'a0103b552f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_names',
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_names_description'), 'rating_names', ['description'], unique=True)
    op.create_table('ratings',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rating_name_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('req_age', sa.Integer(), nullable=True),
    sa.Column('banned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rating_name_id'], ['rating_names.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'rating_name_id', name='uq_game_rating_org')
    )
    op.create_index('idx_ratings_banned', 'ratings', ['banned'], unique=False)
    op.create_index('idx_ratings_game', 'ratings', ['game_id'], unique=False)
    op.create_index('idx_ratings_name', 'ratings', ['rating_name_id'], unique=False)
    op.create_index('idx_ratings_rating', 'ratings', ['rating'], unique=False)
    op.create_index('idx_friends_friend', 'friends', ['friend_id'], unique=False)
    op.create_index('idx_friends_user', 'friends', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_friends_user', table_name='friends')
    op.drop_index('idx_friends_friend', table_name='friends')
    op.drop_index('idx_ratings_rating', table_name='ratings')
    op.drop_index('idx_ratings_name', table_name='ratings')
    op.drop_index('idx_ratings_game', table_name='ratings')
    op.drop_index('idx_ratings_banned', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_rating_names_description'), table_name='rating_names')
    op.drop_table('rating_names')
    # ### end Alembic commands ###
