"""init models

Revision ID: 9e00376e31e7
Revises: 2f93b3291309
Create Date: 2025-10-09 20:59:26.368970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e00376e31e7'
down_revision: Union[str, Sequence[str], None] = '2f93b3291309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_count_history', sa.Column('twitch_viewers', sa.Integer(), nullable=True))
    op.add_column('player_count_history', sa.Column('trend_24h', sa.Float(), nullable=True))
    op.create_index('idx_player_history_game_date', 'player_count_history', ['game_id', 'created_at'], unique=False)
    op.add_column('price_history', sa.Column('price_initial', sa.Integer(), nullable=True))
    op.add_column('price_history', sa.Column('price_original', sa.Integer(), nullable=True))
    op.add_column('price_history', sa.Column('purchase_available', sa.Boolean(), nullable=True))
    op.add_column('price_history', sa.Column('package_id', sa.Integer(), nullable=True))
    op.create_index('idx_price_history_game_date', 'price_history', ['game_id', 'created_at'], unique=False)
    op.drop_column('price_history', 'initial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('initial', sa.INTEGER(), nullable=True))
    op.drop_index('idx_price_history_game_date', table_name='price_history')
    op.drop_column('price_history', 'package_id')
    op.drop_column('price_history', 'purchase_available')
    op.drop_column('price_history', 'price_original')
    op.drop_column('price_history', 'price_initial')
    op.drop_index('idx_player_history_game_date', table_name='player_count_history')
    op.drop_column('player_count_history', 'trend_24h')
    op.drop_column('player_count_history', 'twitch_viewers')
    # ### end Alembic commands ###
