"""Initial tables

Revision ID: a187256e1916
Revises: 
Create Date: 2025-09-29 23:10:44.529708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a187256e1916'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('game_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_types_name'), 'game_types', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('platforms',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('games',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('coming_soon', sa.Boolean(), nullable=True),
    sa.Column('controller_support', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['game_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_games_app_id', 'games', ['app_id'], unique=False)
    op.create_index('idx_games_coming_soon', 'games', ['coming_soon'], unique=False)
    op.create_index('idx_games_free', 'games', ['is_free'], unique=False)
    op.create_index('idx_games_name', 'games', ['name'], unique=False)
    op.create_index('idx_games_release_date', 'games', ['release_date'], unique=False)
    op.create_index('idx_games_type', 'games', ['type_id'], unique=False)
    op.create_index(op.f('ix_games_app_id'), 'games', ['app_id'], unique=True)
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_table('game_categories',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'category_id', name='uq_game_category')
    )
    op.create_index('idx_game_category_category', 'game_categories', ['category_id'], unique=False)
    op.create_index('idx_game_category_game', 'game_categories', ['game_id'], unique=False)
    op.create_table('game_genres',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'genre_id', name='uq_game_genre')
    )
    op.create_index('idx_game_genre_game', 'game_genres', ['game_id'], unique=False)
    op.create_index('idx_game_genre_genre', 'game_genres', ['genre_id'], unique=False)
    op.create_table('game_metrics',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('recommendations_count', sa.Integer(), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('review_score', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('peak_players_all_time', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_index('idx_metrics_players', 'game_metrics', ['peak_players_all_time'], unique=False)
    op.create_index('idx_metrics_review_score', 'game_metrics', ['review_score'], unique=False)
    op.create_table('game_platforms',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'platform_id', name='uq_game_platform')
    )
    op.create_index('idx_game_platform_game', 'game_platforms', ['game_id'], unique=False)
    op.create_index('idx_game_platform_platform', 'game_platforms', ['platform_id'], unique=False)
    op.create_table('player_count_history',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_player_history_date', 'player_count_history', ['recorded_at'], unique=False)
    op.create_index('idx_player_history_game', 'player_count_history', ['game_id'], unique=False)
    op.create_table('price_history',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_final', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_currency', 'price_history', ['currency'], unique=False)
    op.create_index('idx_price_history_date', 'price_history', ['recorded_at'], unique=False)
    op.create_index('idx_price_history_game', 'price_history', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_history_game', table_name='price_history')
    op.drop_index('idx_price_history_date', table_name='price_history')
    op.drop_index('idx_price_history_currency', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_player_history_game', table_name='player_count_history')
    op.drop_index('idx_player_history_date', table_name='player_count_history')
    op.drop_table('player_count_history')
    op.drop_index('idx_game_platform_platform', table_name='game_platforms')
    op.drop_index('idx_game_platform_game', table_name='game_platforms')
    op.drop_table('game_platforms')
    op.drop_index('idx_metrics_review_score', table_name='game_metrics')
    op.drop_index('idx_metrics_players', table_name='game_metrics')
    op.drop_table('game_metrics')
    op.drop_index('idx_game_genre_genre', table_name='game_genres')
    op.drop_index('idx_game_genre_game', table_name='game_genres')
    op.drop_table('game_genres')
    op.drop_index('idx_game_category_game', table_name='game_categories')
    op.drop_index('idx_game_category_category', table_name='game_categories')
    op.drop_table('game_categories')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_index(op.f('ix_games_app_id'), table_name='games')
    op.drop_index('idx_games_type', table_name='games')
    op.drop_index('idx_games_release_date', table_name='games')
    op.drop_index('idx_games_name', table_name='games')
    op.drop_index('idx_games_free', table_name='games')
    op.drop_index('idx_games_coming_soon', table_name='games')
    op.drop_index('idx_games_app_id', table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_game_types_name'), table_name='game_types')
    op.drop_table('game_types')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
