"""update db user, reviews, timeseries & add friends, review history

Revision ID: cb0071f8fa50
Revises: 9e00376e31e7
Create Date: 2025-10-23 21:30:34.655967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0071f8fa50'
down_revision: Union[str, Sequence[str], None] = '9e00376e31e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_developer_name', 'developers', ['name'], unique=False)
    op.create_index(op.f('ix_developers_name'), 'developers', ['name'], unique=False)
    op.create_table('publishers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_publisher_name', 'publishers', ['name'], unique=False)
    op.create_index(op.f('ix_publishers_name'), 'publishers', ['name'], unique=False)
    op.create_table('users',
    sa.Column('steam_id', sa.String(length=17), nullable=False),
    sa.Column('persona_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('last_logoff', sa.DateTime(), nullable=True),
    sa.Column('community_visibility_state', sa.Integer(), nullable=True),
    sa.Column('steam_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_steam_id', 'users', ['steam_id'], unique=False)
    op.create_index(op.f('ix_users_steam_id'), 'users', ['steam_id'], unique=True)
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_id', name='uq_friends_pair')
    )
    op.create_index('idx_friends_friend', 'friends', ['friend_id'], unique=False)
    op.create_index('idx_friends_user', 'friends', ['user_id'], unique=False)
    op.create_table('user_logoff_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_logoff', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logoff_date', 'user_logoff_history', ['last_logoff'], unique=False)
    op.create_index('idx_logoff_user', 'user_logoff_history', ['user_id'], unique=False)
    op.create_table('game_developers',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'developer_id', name='uq_game_developer')
    )
    op.create_index('idx_game_developer_dev', 'game_developers', ['developer_id'], unique=False)
    op.create_index('idx_game_developer_game', 'game_developers', ['game_id'], unique=False)
    op.create_table('game_publishers',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'publisher_id', name='uq_game_publisher')
    )
    op.create_index('idx_game_publisher_game', 'game_publishers', ['game_id'], unique=False)
    op.create_index('idx_game_publisher_pub', 'game_publishers', ['publisher_id'], unique=False)
    op.create_table('reviews',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.String(length=100), nullable=False),
    sa.Column('steam_id', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('timestamp_created', sa.Integer(), nullable=True),
    sa.Column('timestamp_updated', sa.Integer(), nullable=True),
    sa.Column('voted_up', sa.Boolean(), nullable=True),
    sa.Column('votes_up', sa.Integer(), nullable=True),
    sa.Column('votes_funny', sa.Integer(), nullable=True),
    sa.Column('weighted_vote_score', sa.Float(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('steam_purchase', sa.Boolean(), nullable=True),
    sa.Column('received_for_free', sa.Boolean(), nullable=True),
    sa.Column('written_during_early_access', sa.Boolean(), nullable=True),
    sa.Column('primarily_steam_deck', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    op.create_index('idx_reviews_created', 'reviews', ['timestamp_created'], unique=False)
    op.create_index('idx_reviews_game', 'reviews', ['game_id'], unique=False)
    op.create_index('idx_reviews_steam', 'reviews', ['steam_id'], unique=False)
    op.create_index('idx_reviews_user', 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_steam_id'), 'reviews', ['steam_id'], unique=False)
    op.create_table('user_game_ownership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_game_ownership')
    )
    op.create_index('idx_ownership_game', 'user_game_ownership', ['game_id'], unique=False)
    op.create_index('idx_ownership_user', 'user_game_ownership', ['user_id'], unique=False)
    op.create_table('user_playtime',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('playtime_forever', sa.Integer(), nullable=True),
    sa.Column('playtime_2weeks', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='uq_user_playtime')
    )
    op.create_index('idx_playtime_game', 'user_playtime', ['game_id'], unique=False)
    op.create_index('idx_playtime_last_played', 'user_playtime', ['last_played'], unique=False)
    op.create_index('idx_playtime_user', 'user_playtime', ['user_id'], unique=False)
    op.create_table('review_dynamic_data',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.String(length=100), nullable=False),
    sa.Column('voted_up', sa.Boolean(), nullable=True),
    sa.Column('votes_up', sa.Integer(), nullable=True),
    sa.Column('votes_funny', sa.Integer(), nullable=True),
    sa.Column('weighted_vote_score', sa.Float(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'recommendation_id', name='uq_review_dynamic')
    )
    op.create_index('idx_review_dynamic_recommendation', 'review_dynamic_data', ['recommendation_id'], unique=False)
    op.create_index('idx_review_dynamic_review', 'review_dynamic_data', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_dynamic_data_recommendation_id'), 'review_dynamic_data', ['recommendation_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=True),
    sa.Column('unlock_timestamp', sa.Integer(), nullable=True),
    sa.Column('unlock_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', 'achievement_id', name='uq_user_game_achievement')
    )
    op.create_index('idx_user_achievements_game', 'user_achievements', ['game_id'], unique=False)
    op.create_index('idx_user_achievements_unlock_time', 'user_achievements', ['unlock_time'], unique=False)
    op.create_index('idx_user_achievements_user', 'user_achievements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_achievements_user', table_name='user_achievements')
    op.drop_index('idx_user_achievements_unlock_time', table_name='user_achievements')
    op.drop_index('idx_user_achievements_game', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_review_dynamic_data_recommendation_id'), table_name='review_dynamic_data')
    op.drop_index('idx_review_dynamic_review', table_name='review_dynamic_data')
    op.drop_index('idx_review_dynamic_recommendation', table_name='review_dynamic_data')
    op.drop_table('review_dynamic_data')
    op.drop_index('idx_playtime_user', table_name='user_playtime')
    op.drop_index('idx_playtime_last_played', table_name='user_playtime')
    op.drop_index('idx_playtime_game', table_name='user_playtime')
    op.drop_table('user_playtime')
    op.drop_index('idx_ownership_user', table_name='user_game_ownership')
    op.drop_index('idx_ownership_game', table_name='user_game_ownership')
    op.drop_table('user_game_ownership')
    op.drop_index(op.f('ix_reviews_steam_id'), table_name='reviews')
    op.drop_index('idx_reviews_user', table_name='reviews')
    op.drop_index('idx_reviews_steam', table_name='reviews')
    op.drop_index('idx_reviews_game', table_name='reviews')
    op.drop_index('idx_reviews_created', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_game_publisher_pub', table_name='game_publishers')
    op.drop_index('idx_game_publisher_game', table_name='game_publishers')
    op.drop_table('game_publishers')
    op.drop_index('idx_game_developer_game', table_name='game_developers')
    op.drop_index('idx_game_developer_dev', table_name='game_developers')
    op.drop_table('game_developers')
    op.drop_index('idx_logoff_user', table_name='user_logoff_history')
    op.drop_index('idx_logoff_date', table_name='user_logoff_history')
    op.drop_table('user_logoff_history')
    op.drop_index('idx_friends_user', table_name='friends')
    op.drop_index('idx_friends_friend', table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_users_steam_id'), table_name='users')
    op.drop_index('idx_user_steam_id', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_publishers_name'), table_name='publishers')
    op.drop_index('idx_publisher_name', table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_developers_name'), table_name='developers')
    op.drop_index('idx_developer_name', table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###
