"""delete fields from timeseries.PriceHistory

Revision ID: ce8fc3fc1aad
Revises: 19be8adee673
Create Date: 2025-11-29 22:34:08.477011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8fc3fc1aad'
down_revision: Union[str, Sequence[str], None] = '19be8adee673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'purchase_available')
    op.drop_column('price_history', 'price_original')
    op.drop_column('price_history', 'package_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('package_id', sa.INTEGER(), nullable=True))
    op.add_column('price_history', sa.Column('price_original', sa.INTEGER(), nullable=True))
    op.add_column('price_history', sa.Column('purchase_available', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
