"""update timeseries and game

Revision ID: f111d6637ba9
Revises: 9b18da156691
# Revises: ccfbe50ade1d
Create Date: 2025-12-10 22:59:24.244642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f111d6637ba9'
down_revision: Union[str, Sequence[str], None] = '9b18da156691'
# down_revision: Union[str, Sequence[str], None] = 'ccfbe50ade1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('all_time_peak', sa.Integer(), nullable=True))
    op.add_column('player_count_history', sa.Column('date', sa.String(length=20), nullable=True))
    op.add_column('player_count_history', sa.Column('avg_players', sa.Float(), nullable=True))
    op.add_column('player_count_history', sa.Column('percent_gain', sa.Float(), nullable=True))
    op.add_column('player_count_history', sa.Column('gain', sa.Float(), nullable=True))
    op.drop_column('player_count_history', 'twitch_viewers')
    op.drop_column('player_count_history', 'trend_24h')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_count_history', sa.Column('trend_24h', sa.FLOAT(), nullable=True))
    op.add_column('player_count_history', sa.Column('twitch_viewers', sa.INTEGER(), nullable=True))
    op.drop_column('player_count_history', 'gain')
    op.drop_column('player_count_history', 'percent_gain')
    op.drop_column('player_count_history', 'avg_players')
    op.drop_column('player_count_history', 'date')
    op.drop_column('games', 'all_time_peak')
    # ### end Alembic commands ###
